cm.Class.create({$name:"cm.core.BaseObject",$extends:"Object",$define:{tag:"",$super:function(a){cm.equal.isUndefined(this.__currentSuper__)&&(this.__currentSuper__={},this.__calledCount__=0);this.__currentSuper__[a]=cm.equal.isUndefined(this.__currentSuper__[a])?(cm.equal.isUndefined(this.__prevCalledMethodName__),this.$class.superClass):this.__currentSuper__[a].superClass;var b="initialize"==a?this.__currentSuper__[a].prototype.constructor:this.__currentSuper__[a].prototype[a];this.__prevCalledMethodName__=
a;this.__calledCount__++;var c=this;return function(){var d=b.apply(c,arguments);delete c.__currentSuper__[a];"destroy"==a&&delete c.__currentSuper__;0==--c.__calledCount__&&delete c.__prevCalledMethodName__;return d}},$bind:function(a){cm.equal.isUndefined(this.mBindCash)&&(this.mBindCash={});var b=this;cm.equal.isUndefined(this.mBindCash[a])&&(this.mBindCash[a]=function(){b.$class.prototype[a].apply(b,arguments)});return this.mBindCash[a]},BaseObject:function(){++this.$class._instanceCounter},destroy:function(){--this.$class._instanceCounter;
this._deletePropertys()},_deletePropertys:function(){for(var a=cm.object.getOwnPropertyNames(this),b=0,c=a.length;b<c;b++){var d=a[b];if(!("__prevCalledMethodName__"==d||"__calledCount__"==d||"__currentSuper__"==d)){var e=this[d];e&&(cm.equal.isFunction(e.destroy)?e.destroy():cm.equal.isObject(e)||cm.equal.isArray(e)?this._deletePropertys.call(e):(this[d]=null,delete this[d]))}}},getClassFullName:function(){return cm.string.concat(this.classPath,".",this.className)},getSuperClassFullName:function(){return cm.string.concat(this.superClassPath,
".",this.superClassName)},getRefCount:function(){return this.$class._instanceCounter},log:function(){Array.prototype.unshift.call(arguments,this.className);cm.log.p.apply(this,arguments)},equal:function(a){return a===this}}});
cm.Class.create({$name:"cm.core.UserAgent",$singleton:!0,$static:{Vendor:{Unknown:0,WebKit:1,Mozilla:2,MicroSoft:3,Opera:4},Browser:{Unknown:0,Chrome:1,Safari:2,FireFox:3,Mozilla:4,InternetExplorer:5,Opera:6,NetScape:7,Lunascape:8},Platform:{Pc:0,Android:1,iPhone:2,iPad:3,iPod:4,WindowsPhone:5,Symbian:6,BlackBerry:7},VendorPrefix:["","webkit","moz","ms","O"],VendorName:["Unknown","WebKit","Mozilla","MicroSoft","Opera"],BrowserName:"Unknown Chrome Safari FireFox Mozilla InternetExplorer Opera NetScape Lunascape".split(" "),
PlatformName:"Pc Android iPhone iPad iPod WindowsPhone Symbian BlackBerry".split(" ")},$define:{UserAgent:function(){var a=navigator.userAgent;this.vendor=this.getVendor(a);this.vendorPrefix=this.getVendorPrefix();this.platform=this.getPlatform(a);this.platformVersion=this.getPlatformVersion(a);this.browser=this.getBrowser(a);this.browserVersion=this.getBrowserVersion(a)},destroy:function(){},isAndroid:function(){return this.platform==cm.core.UserAgent.Platform.Android},isiPhone:function(){return this.platform==
cm.core.UserAgent.Platform.iPhone},isiPad:function(){return this.platform==cm.core.UserAgent.Platform.iPad},isiPod:function(){return this.platform==cm.core.UserAgent.Platform.iPod},isWindowsPhone:function(){return this.platform==cm.core.UserAgent.Platform.iPod},isMobile:function(){return this.Platform.Pc<this.platform},isRequiredVersionByBrowser:function(a){this._isRequiredVersion(a,this.browserVersion)},isRequiredVersionByPlatform:function(a){this._isRequiredVersion(a,this.platformVersion)},_isRequiredVersion:function(a,
b){for(var c=(void 0===b?0:b).toString().sprit("."),d=b.toString().split(".");0<d.length&&0<c.length;){var e=d.shift(),f=c.shift();if(f<e)return!0;if(f>e)break}return!1},getVendor:function(a){return a.match(/opera/i)?cm.core.UserAgent.Vendor.Opera:a.match(/msie/i)?cm.core.UserAgent.Vendor.MicroSoft:a.match(/webkit/i)?cm.core.UserAgent.Vendor.WebKit:a.match(/(gecko|mozilla)/i)?cm.core.UserAgent.Vendor.Mozilla:cm.core.UserAgent.Vendor.Unknown},getVendorName:function(){return cm.core.UserAgent.VendorName[this.vendor]},
getPlatform:function(a){return a.match(/android/i)?cm.core.UserAgent.Platform.Android:a.match(/ipod/i)?cm.core.UserAgent.Platform.iPod:a.match(/iphone/i)?cm.core.UserAgent.Platform.iPhone:a.match(/ipad/i)?cm.core.UserAgent.Platform.iPad:a.match(/windows phone/i)?cm.core.UserAgent.Platform.WindowsPhone:a.match(/blackberry/i)?cm.core.UserAgent.Platform.BlackBerry:a.match(/symbian/i)?cm.core.UserAgent.Platform.Symbian:cm.core.UserAgent.Platform.Pc},getPlatformName:function(){return cm.core.UserAgent.PlatformName[this.platform]},
getPlatformVersion:function(a){a=a.toLowerCase();switch(this.getPlatform(a)){case cm.core.UserAgent.Platform.Pc:return"0";case cm.core.UserAgent.Platform.Android:var b=a.match(/android ?[0-9|\.]+[;|-]/);return b?a.match(/android ?[0-9|\.]+[;|-]/)[0].toString().replace("android","").replace(" ","").replace("-","").replace(";",""):"0";case cm.core.UserAgent.Platform.iPhone:case cm.core.UserAgent.Platform.iPad:return a.match(/os ?[0-9|_]+ ?like/)[0].toString().split("_").join(".").replace("_",".").replace("os",
"").replace(" ","").replace("like","");case cm.core.UserAgent.Platform.iPod:return a.match(/mobile\/3a100a/)?"2.0":a.match(/os ?[0-9|_]+? ?like/)[0].toString().split("_").join(".").replace("_",".").replace("os","").replace(" ","").replace("like","");case cm.core.UserAgent.Platform.WindowsPhone:return a.match(/windows phone (os )?[0-9|\.]+;?/)[0].toString().replace("windows phone ","").replace("os ","").replace(";","");case cm.core.UserAgent.Platform.BlackBerry:return(b=a.match(/blackberry ?[0-9]+;?/))?
b[0].toString().replace("blackberry","").replace(" ",""):"0";case cm.core.UserAgent.Platform.Symbian:return a.match(/symbian(os)?\/[0-9|\.]+;?/)[0].toString().replace("symbian","").replace("os","").replace("/","").replace(";","")}},getBrowser:function(a){return a.match(/opera/i)?cm.core.UserAgent.Browser.Opera:a.match(/firefox/i)?cm.core.UserAgent.Browser.FireFox:a.match(/netscape/i)?cm.core.UserAgent.Browser.NetScape:a.match(/lunascape/i)?cm.core.UserAgent.Browser.Lunascape:a.match(/chrome/i)?cm.core.UserAgent.Browser.Chrome:
a.match(/safari|Mobile\/8L1|Mobile\/7B405|Mobile\/8C134/i)?cm.core.UserAgent.Browser.Safari:a.match(/msie/i)?cm.core.UserAgent.Browser.InternetExplorer:a.match(/mozilla/i)?cm.core.UserAgent.Browser.Mozilla:cm.core.UserAgent.Browser.Unknown},getBrowserName:function(){return cm.core.UserAgent.BrowserName[this.browser]},getBrowserVersion:function(a){a=a.toLowerCase();switch(this.getBrowser(a)){case cm.core.UserAgent.Browser.Unknown:return"0";case cm.core.UserAgent.Browser.Opera:var b=a.match(/^opera\/[0-9|\.]+/);
return b?(b=b[0].toString(),b.match(/9.80/)?a.match(/version\/[0-9|\.]+/)[0].toString().replace("version/",""):b.replace("opera/","")):a.match(/opera ?[0-9|\.]+ ?/)[0].toString().replace("opera","").replace(" ","");case cm.core.UserAgent.Browser.FireFox:return a.match(/firefox\/[0-9|\.]+/)[0].toString().replace("firefox/","");case cm.core.UserAgent.Browser.NetScape:return(b=a.match(/netscape6\/[0-9|\.]+/))?b[0].toString().replace("netscape6/",""):a.match(/netscape\/[0-9|\.]+/)[0].toString().replace("netscape/",
"");case cm.core.UserAgent.Browser.Mozilla:return(b=a.match(/mozilla\/[0-4]\.[0-9|\.]+/))?b[0].toString().replace("mozilla/",""):(b=a.match(/gecko\/[0-9]+/))?b[0].toString().replace("gecko/",""):"0";case cm.core.UserAgent.Browser.Lunascape:return a.match(/lunascape ?[0-9|\.]+/)[0].toString().replace("lunascape","").replace(" ","");case cm.core.UserAgent.Browser.Chrome:return a.match(/chrome\/[0-9|\.]+/)[0].toString().replace("chrome/","");case cm.core.UserAgent.Browser.Safari:return(b=a.match(/applewebkit\/(85|[1-3][0-9\.]+)/))?
"1.0":a.match(/applewebkit\/4[0-9\.]+/)?"2.0":(b=a.match(/version\/[0-9\.]+/))?b[0].toString().replace("version/",""):"0";case cm.core.UserAgent.Browser.InternetExplorer:return a.match(/msie ?[0-9|\.]+/)[0].toString().replace("msie","").replace(" ","")}},getVendorPrefix:function(){return cm.core.UserAgent.VendorPrefix[this.vendor]}}});
cm.Class.create("cm.event.Event","cm.loaderImpl.HtmlDomLoaderImpl","cm.loaderImpl.HtmlDomOption","cm.loaderImpl.AjaxLoaderImpl","cm.loaderImpl.AjaxOption","cm.core.BrowserInterface",{$name:"cm.core.LoaderInterface",$extends:"cm.event.EventDispatcher",$singleton:!0,$define:{LoaderInterface:function(){cm.loader=this;this.templateOption={ajax:new cm.loaderImpl.AjaxOption,htmlDom:new cm.loaderImpl.HtmlDomOption};this.mAjaxLoader=new cm.loaderImpl.AjaxLoaderImpl;this.mDomLoader=new cm.loaderImpl.HtmlDomLoaderImpl;
this.mLoading={};this.mComplete={};this.mError={};this.mTimeout={};this.mRequestGroups=[]},destroy:function(){},isRunning:function(){return 0<this.mRequestGroups.length},addRequestGroup:function(a){-1<this.mRequestGroups.indexOf(a)||(this.mRequestGroups.push(a),this._resumeRequestGroup(a)?this.mRequestGroups.pop():a.notifyLoading())},_resumeRequestGroup:function(a){for(var b,c;!cm.equal.isNull(b=a.shiftRequire());)if(cm.equal.isUndefined(this.mLoading[b])){c=b[0];var d;cm.equal.isUndefined(this.mError[c])?
cm.equal.isUndefined(this.mTimeout[c])?cm.equal.isUndefined(this.mComplete[c])||(d=a.updateByProgress(c,1)):d=a.updateByTimeout(c):d=a.updateByError(c);if(d)return!0;this._request.apply(this,b)}return!1},_request:function(a,b,c){a=cm.dom.toAbsolutePath(a);var d=this.mDomLoader,e=cm.equal.isUndefined(c)?this.templateOption.htmlDom:c,e=d.create(a,b,e);cm.equal.isNull(e)&&(d=this.mAjaxLoader,e=cm.equal.isUndefined(c)?this.templateOption.ajax:c,e=d.create(a,b,e));cm.equal.isUndefined(this.mLoading[a])&&
(this.mLoading[a]=e);d.request(e)},removeRequestGroup:function(a){a=this.mRequestGroups.indexOf(a);-1<a&&this.mRequestGroups.splice(a,1)},clearRequestGroups:function(){for(this.mLoading={};this.isRunning();)this.mRequestGroups.unshift().destroy();for(var a in this.mLoading)cm.equal.isFunction(this.mLoading[a].abort)&&this.mLoading[a].abort()},getCache:function(a){a=cm.dom.toAbsolutePath(a);return!cm.equal.isUndefined(this.mComplete[a])?this.mComplete[a]:!cm.equal.isUndefined(this.mLoading[a])?this.mLoading[a]:
!cm.equal.isUndefined(this.mError[a])?this.mError[a]:!cm.equal.isUndefined(this.mTimeout[a])?this.mTimeout[a]:null},clearCache:function(a){cm.equal.isUndefined(a)?(this.mComplete={},this.mError={},this.mTimeout={}):(delete this.mComplete[a],delete this.mError[a],delete this.mTimeout[a])},stateChangeByProgress:function(a,b){for(var c=this.mRequestGroups,d=0,e=c.length;d<e;d++)c[d].updateByProgress(a,b)},stateChangeByError:function(a){this.mError[a]=this.mLoading[a];delete this.mLoading[a];for(var b=
this.mRequestGroups,c=0;c<b.length;c++)b[c].updateByError(a)&&b.splice(c--,1);this.dispatchEvent(cm.event.Event.ERROR,a)},stateChangeByTimeout:function(a){this.mTimeout[a]=this.mLoading[a];delete this.mLoading[a];for(var b=this.mRequestGroups,c=0;c<b.length;c++)b[c].updateByTimeout(a)&&b.splice(c--,1);this.dispatchEvent(cm.event.Event.TIMEOUT,a)},stateChangeByComplete:function(a){this.mComplete[a]=this.mLoading[a];delete this.mLoading[a];for(var b=this.mRequestGroups,c=0;c<b.length;c++)b[c].updateByProgress(a,
1)&&b.splice(c--,1)}}});
cm.Class.create({$name:"cm.event.Event",$static:{INIT:"init",ACTIVATE:"activate",DEACTIVATE:"deactivate",CANCEL:"cancel",CLEAR:"clear",CONNECT:"connect",FULLSCREEN:"fullScreen",OPEN:"open",CLOSING:"closing",SELECT_ALL:"selectAll",UPDATE:"update",COMPLETE:"complete",SOUND_COMPLETE:"soundComplete",CONTEXT_MENU:"contextMenu",ABORT:"abort",LOAD:"load",UNLOAD:"unload",ERROR:"error",RESIZE:"resize",SCROLL:"scroll",BEFORE_UNLOAD:"beforeUnload",CLOSE:"close",SELECT:"select",CHANGE:"change",SUBMIT:"submit",
RESET:"reset",FOCUS:"focus",BLUR:"blur",COPY:"copy",CUT:"cut",PASTE:"paste",KEY_DOWN:"keyDown",KEY_PRESS:"keyPress",KEY_UP:"keyUp",DRUG_DROP:"drugDrop",CLICK:"click",DOUBLE_CLICK:"doubleClick",MOUSE_DOWN:"mouseDown",MOUSE_MOVE:"mouseMove",MOUSE_OUT:"mouseOut",MOUSE_OVER:"mouseOver",MOUSE_WHEEL:"mouseWheel",MOUSE_UP:"mouseUp",LOAD_START:"loadStart",LOAD_END:"loadEnd",PROGRESS:"progress",TIMEOUT:"timeout"},$define:{Event:function(a,b){this.target=a;this.type=b},destroy:function(){this.target=this.type=
null}}});
cm.Class.create("cm.core.BrowserInterface",{$name:"cm.loaderImpl.RequestGroup",$extends:"cm.event.EventDispatcher",$define:{RequestGroup:function(){this.mIsRunning=!1;this.mTotalRequestNum=0;this.mRequires={};this.mProgress={};this.mErrors=[];this.mTimeouts=[]},destroy:function(){},_hasUrl:function(a){return!cm.equal.isUndefined(this.mRequires[a])},addRequire:function(a,b,c){this.mIsRunning&&cm.log.e("addRequire is canceled. this object is aleady run.");a=cm.dom.toAbsolutePath(a);this._hasUrl(a)||(this.mTotalRequestNum++,
this.mRequires[a]=arguments);return this},removeRequire:function(a){this.mIsRunning&&cm.log.e("removeRequire is canceled. this object is aleady run.");a=cm.dom.toAbsolutePath(a);this._hasUrl(a)&&(this.mTotalRequestNum--,delete this.mRequires[a]);return this},clone:function(){var a=new this.$class;a.mTotalRequestNum=this.mTotalRequestNum;for(var b in this.mRequires)a.mRequires[b]=this.mRequires[b];return a},notifyLoading:function(){this.mIsRunning=!0},shiftRequire:function(){for(var a in this.mRequires){var b=
this.mRequires[a];delete this.mRequires[a];return b}return null},updateByError:function(a){this.mErrors.push(a);return this.updateByProgress(a,0)},updateByTimeout:function(a){this.mTimeouts.push(a);return this.updateByProgress(a,0)},updateByProgress:function(a,b){this.mProgress[a]=b;var c=this._calcProgress(),d=1<=c;d?(this.dispatchEvent(cm.event.Event.COMPLETE,{error:this.mErrors.slice(0),timeout:this.mTimeouts.slice(0)}),this.destroy()):(this.dispatchEvent(cm.event.Event.PROGRESS,c),1==b&&this.dispatchEvent(cm.event.Event.UPDATE,
a));return d},_calcProgress:function(){var a=0,b;for(b in this.mProgress)a+=this.mProgress[b];return a/(this.mTotalRequestNum-this.mErrors.length-this.mTimeouts.length)}}});
cm.Class.create("cm.event.Event","cm.util.Dictionary",{$name:"cm.event.EventDispatcher",$define:{EventDispatcher:function(a){this.m_self=a?a:this},_runtimeInitialize:function(){this.m_eventStream={};this.m_callbacks=new cm.util.Dictionary;this.m_listenerCount=0;this.addEventListener=this.__addEventListener;this.hasEventListener=this.__hasEventListener;this.dispatchEvent=this.__dispatchEvent},destroy:function(){this.m_self=this.m_eventStream=null},hasEventListener:function(a,b,c){this._runtimeInitialize();
this.hasEventListener.call(this,a,b,c)},__hasEventListener:function(a,b,c){this.m_hasIndex=-1;this.m_hasData=this.m_callbacks.get(b);if(void 0===this.m_hasData)return!1;b=this.m_hasData[a];if(void 0===b)return Boolean(void 0===a);if(void 0===c)return!0;a=0;for(var d=b.length;a<d;a++)if(b[a]===c)return this.m_hasIndex=a,!0;return!1},dispatchEvent:function(){this._runtimeInitialize();this.dispatchEvent.apply(this,arguments)},__dispatchEvent:function(){var a=this.m_eventStream[Array.prototype.shift.apply(arguments)];
if(a)for(var b=0,c=a.length;b<c;b++)a[b].bindCallback.apply(this,arguments)},addEventListener:function(){this._runtimeInitialize();this.addEventListener.apply(this,arguments)},__addEventListener:function(){3>arguments.length&&cm.log.e("Arguments Error.");var a=arguments[0],b=arguments[1],c=arguments[2],d=arguments[3];this.hasEventListener(a,b,c)||(this._addCallbackFromArray(a,b,c),this._addCallbackFromStream(a,b,c,d),delete this.m_hasData,delete this.m_hasIndex,this.m_listenerCount++)},removeEventListener:function(a,
b,c){this.hasEventListener(a,b,c)&&(this._removeCallbackFromStream(a),this._removeCallbackFromArray(a,b),delete this.m_hasData,delete this.m_hasIndex,this.m_listenerCount--)},getListenerCount:function(){return this.m_listenerCount},_addCallbackFromArray:function(a,b,c){var d=this.m_hasData;void 0===d?(d={},d[a]=[c],this.m_callbacks.set(b,d)):(b=d[a],void 0===b?d[a]=[c]:b.push(c))},_addCallbackFromStream:function(a,b,c,d){var e=this.m_eventStream[a];d={priority:void 0===d?0:d,callback:c,bindCallback:function(){var d=
new cm.event.Event(this,a);Array.prototype.unshift.call(arguments,d);c.apply(b,arguments);d.destroy()}};if(void 0===e)this.m_eventStream[a]=[],this.m_eventStream[a].push(d);else{for(var f=0,g=e.length;f<g;f++)if(e[f].priority<d.priority){e.splice(f,0,d);return}e.push(d)}},_removeCallbackFromStream:function(a){for(var b=this.m_eventStream[a],c=this.m_hasData[a][this.m_hasIndex],d=0,e=b.length;d<e;d++)if(b[d].callback===c){b.splice(d,1);0==b.length&&delete this.m_eventStream[a];break}},_removeCallbackFromArray:function(a,
b){var c=this.m_hasData,d=c[a];d.splice(this.m_hasIndex,1);if(0==d.length){delete c[a];for(var e in c)return;this.m_callbacks.del(b)}}}});
cm.Class.create("cm.util.UpdateDispatcher","cm.core.BrowserInterface",{$name:"cm.loaderImpl.HtmlDomLoaderImpl",$extends:"cm.loaderImpl.AbsLoaderImpl",$define:{HtmlDomLoaderImpl:function(){this.mExtensions={img:/^(gif|jpeg|jpg|png)/i,video:/^(264|3g2|3gp|3gpp|avc|avi|h264|m4v|mkv|mp4|mpeg|mpg|ogg|ogv|webm)/i,audio:/^(aac|m4a|mp3|oga|ogg|wav)/i}},destroy:function(){},create:function(a,b,c){var d=this._switchTagName(a.split(".").pop());if(cm.equal.isNull(d))return null;d=cm.dom.d.createElement(d);this.initializeLoader(d);
this.attachCustomProperty(d,a,b,c);return d},_switchTagName:function(a){for(var b in this.mExtensions)if(a.match(this.mExtensions[b]))return b;return null},request:function(a){var b=a.cmArgumentsCache,c=b[0],b=b[1];this.$super("request")(a);a.src=c+b},initializeLoader:function(a){cm.dom.addEventListener(cm.event.Event.LOAD,a,this.$bind("onComplete"),!0);cm.dom.addEventListener(cm.event.Event.ERROR,a,this.$bind("onError"),!0)},resetLoader:function(a){this.$super("resetLoader")(a);cm.dom.removeEventListener(cm.event.Event.LOAD,
a,this.$bind("onComplete"),!0);cm.dom.removeEventListener(cm.event.Event.ERROR,a,this.$bind("onError"),!0);this.detachCustomProperty(a)},onError:function(a){this.$super("onError")(a.target)},onComplete:function(a){this.$super("onComplete")(a.target)}}});cm.Class.create({$name:"cm.loaderImpl.HtmlDomOption",$define:{HtmlDomOption:function(){this.timeout=15E3;this.retry=1},destroy:function(){}}});
cm.Class.create("cm.core.BrowserInterface",{$name:"cm.loaderImpl.AjaxLoaderImpl",$extends:"cm.loaderImpl.AbsLoaderImpl",$define:{AjaxLoaderImpl:function(){},destroy:function(){},create:function(a,b,c){var d=cm.dom.createXhr();this.initializeLoader(d);this.attachCustomProperty(d,a,b,c);return d},request:function(a){var b=a.cmArgumentsCache,c=b[0],d=b[1],b=b[2],e=b.method.toUpperCase();this.$super("request")(a);a.requestType=b.requestType;a.withCredentials=b.withCredentials;if(e.match(/^POST$/))a.open(e,
url,b.async),this._setRequestHeader(a,b.header),a.send(d);else{try{a.open(e,c+((""==d?"":"?")+d),b.async)}catch(f){this.log(f.message);return}this._setRequestHeader(a,b.header);a.send(null)}},_setRequestHeader:function(a,b){if("setRequestHeader"in a)for(var c in b)a.setRequestHeader(c,b[c]);else cm.log.w("XDR is No custom headers may be added to the request")},initializeLoader:function(a){var b=this.$bind("onComplete"),c=this.$bind("_onStatechange"),d=this.$bind("onProgress");a.onload=function(){b({target:this})};
a.onreadystatechange=function(){c(this)};a.onprogress=function(){d(this)}},resetLoader:function(a){this.$super("resetLoader")(a);a.onload=null;a.onprogress=null;a.onreadystatechange=null;this.detachCustomProperty(a)},_onStatechange:function(a){4==a.readyState&&(200==a.status?this.onComplete({target:a}):this.onError({target:a}))},onProgress:function(a){if(!cm.equal.isUndefined(a.lengthComputable)&&a.lengthComputable){var b=a.target;this.$super("onProgress")(b.cmArgumentsCache[0],a.loaded/a.total)}},
onTimeout:function(a){a.abort();this.$super("onTimeout")(a)},onError:function(a){this.$super("onError")(a.target)},onComplete:function(a){this.$super("onComplete")(a.target)}}});cm.Class.create({$name:"cm.loaderImpl.AjaxOption",$define:{AjaxOption:function(){this.timeout=15E3;this.requestType="text";this.method="GET";this.retry=3;this.async=!0;this.withCredentials=!1;this.header={}},destroy:function(){}}});
cm.Class.create("cm.domImpl.OperaDomImpl","cm.domImpl.FireFoxDomImpl","cm.domImpl.ChromeSafariDomImpl","cm.domImpl.InternetExplorerDomImpl","cm.cssImpl.OperaCssImpl","cm.cssImpl.FireFoxCssImpl","cm.cssImpl.ChromeSafariCssImpl","cm.cssImpl.InternetExplorerCssImpl",{$name:"cm.core.BrowserInterface",$singleton:!0,$define:{BrowserInterface:function(){this._switchImpl()},_switchImpl:function(){var a=cm.core.UserAgent;switch(a.browser){case a.Browser.InternetExplorer:cm.log.$("browser internetExplorer");
new cm.domImpl.InternetExplorerDomImpl;new cm.cssImpl.InternetExplorerCssImpl;break;case a.Browser.FireFox:cm.log.$("browser firefox");new cm.domImpl.FireFoxDomImpl;new cm.cssImpl.FireFoxCssImpl;break;case a.Browser.Chrome:case a.Browser.Safari:cm.log.$("browser chrome or safari");new cm.domImpl.ChromeSafariDomImpl;new cm.cssImpl.ChromeSafariCssImpl;break;case a.Browser.Opera:cm.log.$("browser opera");new cm.domImpl.OperaDomImpl;new cm.cssImpl.OperaCssImpl;break;default:cm.log.$("browser unknown"),
new cm.domImpl.AbsDomImpl,new cm.cssImpl.AbsCssImpl}},destroy:function(){}}});
cm.Class.create({$name:"cm.util.Dictionary",$define:{Dictionary:function(){},_runtimeInitialize:function(){this.m_value=[];this.m_key=[];this.m_empty=[];this.get=this._get;this.set=this._set;this.del=this._del},destroy:function(){this.m_value=this.m_key=null},get:function(a){this._runtimeInitialize();this.get(a)},_get:function(a){return this.m_value[this._getValIndex(a)]},set:function(a,b){this._runtimeInitialize();this.set(a,b)},_set:function(a,b){var c=this._getValIndex(a),c=-1<c?c:this._getNewIndex();
this.m_key[c]=a;this.m_value[c]=b},forEach:function(){for(var a=Array.prototype.shift.call(arguments),b=0,c=this.m_key.length;b<c;b++)cm.equal.isUndefined(this.m_key[b])||a(this.m_key[b],this.m_value[b],arguments)},del:function(a){this._runtimeInitialize();this.del(a)},_del:function(a){a=this._getValIndex(a);-1<a&&(this.m_key[a]=this.m_value[a]=void 0,this.m_empty.push(a))},m_value:null,m_key:null,m_empty:null,_getValIndex:function(a){for(var b=0,c=this.m_key.length;b<c;b++)if(this.m_key[b]===a)return b;
return-1},_getNewIndex:function(){return 0<this.m_empty.length?this.m_empty.shift():this.m_value.length}}});
cm.Class.create("cm.core.LoaderInterface",{$name:"cm.loaderImpl.AbsLoaderImpl",$define:{AbsLoaderImpl:function(){this.mTimer={};cm.util.UpdateDispatcher.addUpdater(this)},destroy:function(){cm.util.UpdateDispatcher.removeUpdater(this)},create:function(){},request:function(a){var b=a.cmArgumentsCache;this.mTimer[b[0]]=b[2].timeout;return a},initializeLoader:function(){},resetLoader:function(a){delete this.mTimer[a.cmArgumentsCache[0]]},attachCustomProperty:function(a,b,c,d){c=this.objectToQuery(c);
a.cmRetry=d.retry;a.cmArgumentsCache=Array.prototype.slice.call(arguments,1)},detachCustomProperty:function(a){a.cmRetry=void 0;a.cmArgumentsCache=void 0},objectToQuery:function(a){var b="";if(cm.equal.isObject(a))for(var c in a)b+=cm.string.concat(""==b?"":"&",c,"=",encodeURI(a[c]));return b},onProgress:function(a,b){cm.core.LoaderInterface.stateChangeByProgress(a,b)},onTimeout:function(a){0==--a.cmRetry?(cm.core.LoaderInterface.stateChangeByTimeout(a.cmArgumentsCache[0]),this.resetLoader(a)):this.request.apply(this,
[a])},onError:function(a){cm.core.LoaderInterface.stateChangeByError(a.cmArgumentsCache[0]);this.resetLoader(a)},onComplete:function(a){cm.core.LoaderInterface.stateChangeByComplete(a.cmArgumentsCache[0]);this.resetLoader(a)},_update:function(a,b){for(var c in this.mTimer)if(0>(this.mTimer[c]-=b))this.onTimeout(cm.core.LoaderInterface.getCache(c));return!0}}});
cm.Class.create({$name:"cm.util.UpdateDispatcher",$singleton:!0,$define:{UpdateDispatcher:function(){this.intervalId=null;this._enabledUpdaters=[];this._disabledUpdaters=[];this.start()},destroy:function(){this.stop();this._enabledUpdaters=this._disabledUpdaters=null},start:function(){this.stop();this.latestDateNow=Date.now();this.delta=this.elapsed=0;var a=this;this.intervalId=setInterval(function(){a.dispatch()},1E3/60)},stop:function(){cm.equal.isNull(this.intervalId)||(clearInterval(this.intervalId),
this.intervalId=null)},addUpdater:function(a){0>this._enabledUpdaters.indexOf(a)?this._enabledUpdaters.push(a):(a=this._disabledUpdaters.indexOf(a),0<=a&&this._disabledUpdaters.splice(a,1))},removeUpdater:function(a){0>this._disabledUpdaters.indexOf(a)&&this._disabledUpdaters.push(a)},dispatch:function(){this._refreshEnabledUpdaters();var a=this._enabledUpdaters,b=Date.now();this.elapsed=b-this.latestDateNow;this.delta+=this.elapsed;this.latestDateNow=b;for(var b=0,c=a.length;b<c;b++)a[b]._update(this.delta,
this.elapsed)||(a.splice(b,1),--b,--c)},_refreshEnabledUpdaters:function(){for(;0<this._disabledUpdaters.length;){var a=this._enabledUpdaters.indexOf(this._disabledUpdaters.shift());0<=a&&this._enabledUpdaters.splice(a,1)}}}});cm.Class.create({$name:"cm.domImpl.OperaDomImpl",$extends:"cm.domImpl.AbsDomImpl",$define:{OperaDomImpl:function(){},destroy:function(){},_isWheelDown:function(){return 0>-1*this.detail},_isWheelUp:function(){return 0<-1*this.detail}}});
cm.Class.create({$name:"cm.domImpl.FireFoxDomImpl",$extends:"cm.domImpl.AbsDomImpl",$define:{FireFoxDomImpl:function(){},destroy:function(){},_overrideEventDefine:function(){this.$super("_overrideEventDefine")();cm.event.Event.MOUSE_WHEEL="DOMMouseScroll"},_DOMMouseScroll:this._mousewheel,_isWheelDown:function(){return 0<this.detail},_isWheelUp:function(){return 0>this.detail}}});
cm.Class.create({$name:"cm.domImpl.ChromeSafariDomImpl",$extends:"cm.domImpl.AbsDomImpl",$define:{ChromeSafariDomImpl:function(){},destroy:function(){}}});
cm.Class.create("cm.event.Event",{$name:"cm.domImpl.InternetExplorerDomImpl",$extends:"cm.domImpl.AbsDomImpl",$define:{InternetExplorerDomImpl:function(){this.mActivator=cm.dom.d.getElementsByTagName("script")[0];if(7>cm.core.UserAgent.browserVersion&&cm.equal.isFunction(cm.onWarningUpgrade))cm.onWarningUpgrade();7<cm.core.UserAgent.browserVersion&&(this.w.XMLHttpRequest=function(){cm.log.d("create XDomainRequest");return new XDomainRequest})},destroy:function(){},_overrideEventDefine:function(){if(8>
cm.core.UserAgent.browserVersion){var a=cm.event.Event;a.CONTEXT_MENU="oncontextmenu";a.ABORT="onabort";a.LOAD="onload";a.UNLOAD="onunload";a.ERROR="onerror";a.RESIZE="onresize";a.SCROLL="onscroll";a.BEFORE_UNLOAD="onbeforeunload";a.CLOSE="onclose";a.SELECT="onselect";a.CHANGE="onchange";a.SUBMIT="onsubmit";a.RESET="onreset";a.FOCUS="onfocus";a.BLUR="onblur";a.COPY="oncopy";a.CUT="oncut";a.PASTE="onpaste";a.KEY_DOWN="onkeydown";a.KEY_PRESS="onkeypress";a.KEY_UP="onkeyup";a.DRUG_DROP="ondrugdrop";
a.CLICK="onclick";a.DOUBLE_CLICK="ondblclick";a.MOUSE_DOWN="onmousedown";a.MOUSE_MOVE="onmousemove";a.MOUSE_OUT="onmouseout";a.MOUSE_OVER="onmouseover";a.MOUSE_WHEEL="onmousewheel";a.MOUSE_UP="onmouseup";a.LOAD_START="onloadstart";a.LOAD_END="onloadend";a.PROGRESS="onprogress";a.TIMEOUT="ontimeout"}},addEventListener:function(a,b,c,d){this._tryActivateElement(b);var e=function(d){cm.dom.$bind("_attachCustomPropertyToEventObject")(a,d,arguments.callee);var e=c(d);cm.dom.$bind("_tryDeactivateElement")(b);
return e};8>cm.core.UserAgent.browserVersion?b.attachEvent(a,e):b.addEventListener(a,e,d);return e},_attachCustomPropertyToEventObject:function(a,b,c){this.$super("_attachCustomPropertyToEventObject")(a,b,c);b.target=b.srcElement;b.preventDefault||(b.preventDefault=this._preventDefault);b.stopPropagation||(b.stopPropagation=this._stopPropagation)},_tryActivateElement:function(a){!cm.equal.isUndefined(a.nodeType)&&(1==a.nodeType&&cm.equal.isNull(a.parentNode))&&(a.cmActivate=!0,this.mActivator.parentNode.insertBefore(a,
this.mActivator))},_tryDeactivateElement:function(a){a.cmActivate&&(a.cmActivate=void 0,a.parentNode===this.mActivator&&this.mActivator.removeChild(a))},_preventDefault:function(){this.returnValue=!1},_stopPropagation:function(){this.cancelBubble=!1},removeEventListener:function(a,b,c,d){8>cm.core.UserAgent.browserVersion?b.detachEvent(a,c):b.removeEventListener(a,c,d)}}});cm.Class.create({$name:"cm.cssImpl.OperaCssImpl",$extends:"cm.cssImpl.AbsCssImpl",$define:{OperaCssImpl:function(){},destroy:function(){}}});
cm.Class.create({$name:"cm.cssImpl.FireFoxCssImpl",$extends:"cm.cssImpl.AbsCssImpl",$define:{FireFoxCssImpl:function(){},destroy:function(){},getGradientCssText:function(a,b,c){c=cm.string.concat("-moz-linear-gradient(",c,", ",a[0]);for(var d=1,e=0,f=b.length;e<f;e++)d+=b[e];e=0;for(f=a.length-1;e<f;e++)c+=cm.string.concat(", #",a.toString(16)," ",b[e]/d);cm.string.concat(", #",a[a.length-1].toString(16),");");return _csstext}}});
cm.Class.create({$name:"cm.cssImpl.ChromeSafariCssImpl",$extends:"cm.cssImpl.AbsCssImpl",$define:{ChromeSafariCssImpl:function(){},destroy:function(){},gradientToString:function(a){var b=a.beginColor(),c=a.colors();a=a.threshold();for(var d=0,e=cm.string.concat("-webkit-gradient(linear, left bottom, left top, from(",this.colorToRgbaString(b),")"),f=0,g=c.length-1;f<g;f++)b=c[f],d+=a[f],e+=cm.string.concat(", color-stop(",d,", ",this.colorToRgbaString(b),")");b=c[c.length-1];return e+=cm.string.concat(", to(",
this.colorToRgbaString(b),"))")}}});
cm.Class.create({$name:"cm.cssImpl.InternetExplorerCssImpl",$extends:"cm.cssImpl.AbsCssImpl",$define:{InternetExplorerCssImpl:function(){this.mCss=document.createStyleSheet();this.mCss.cssText="css"},destroy:function(){},computedStyle:function(a){return a.currentStyle},ruleLength:function(){return this.mCss.rules.length},getRule:function(a){return this.mCss.rules[a]},appendRule:function(a,b,c){this.mCss.addRule(a,b,c)},removeRule:function(a){this.mCss.removeRule(a)},modifyRule:function(a,b){this.log(a,
this.mCss.rules[a].style.cssText);this.mCss.rules[a].style.cssText=b},getGradientCssText:function(){return""}}});
cm.Class.create("cm.event.Event",{$name:"cm.domImpl.AbsDomImpl",$define:{AbsDomImpl:function(){cm.dom=this;this.w=window;this.d=document;this.mPathConverter=this.d.createElement("p");this._overrideEventDefine();this._createFookMethodAliace()},destroy:function(){},_overrideEventDefine:function(){var a=cm.event.Event;a.CONTEXT_MENU="contextmenu";a.ABORT="abort";a.LOAD="load";a.UNLOAD="unload";a.ERROR="error";a.RESIZE="resize";a.SCROLL="scroll";a.BEFORE_UNLOAD="beforeunload";a.CLOSE="close";a.SELECT=
"select";a.CHANGE="change";a.SUBMIT="submit";a.RESET="reset";a.FOCUS="focus";a.BLUR="blur";a.COPY="copy";a.CUT="cut";a.PASTE="paste";a.KEY_DOWN="keydown";a.KEY_PRESS="keypress";a.KEY_UP="keyup";a.DRUG_DROP="drugdrop";a.CLICK="click";a.DOUBLE_CLICK="dblclick";a.MOUSE_DOWN="mousedown";a.MOUSE_MOVE="mousemove";a.MOUSE_OUT="mouseout";a.MOUSE_OVER="mouseover";a.MOUSE_WHEEL="mousewheel";a.MOUSE_UP="mouseup";a.LOAD_START="loadstart";a.LOAD_END="loadend";a.PROGRESS="progress";a.TIMEOUT="timeout"},_createFookMethodAliace:function(){var a=
cm.event.Event;this.mFookMethodAliace={};this.mFookMethodAliace[a.MOUSE_WHEEL]=this._mousewheel},addEventListener:function(a,b,c,d){var e=function(b){cm.dom.$bind("_attachCustomPropertyToEventObject")(a,b,arguments.callee,d);return c(b)};b.addEventListener(a,e,d);return e},_attachCustomPropertyToEventObject:function(a,b,c,d){b.callee=c;b.useCapture=d;b.removeEventListener=this.removeEventListenerFromInner;(a=this.mFookMethodAliace[a])&&a.call(this,b)},_mousewheel:function(a){a.isWheelDown=this._isWheelDown;
a.isWheelUp=this._isWheelUp},_isWheelDown:function(){return 0>this.wheelDelta},_isWheelUp:function(){return 0<this.wheelDelta},removeEventListenerFromInner:function(){cm.dom.removeEventListener(this.type,this.target,this.callee,this.useCapture)},removeEventListener:function(a,b,c,d){b.removeEventListener(a,c,d)},getX:function(a){return a.offsetLeft},getY:function(a){return a.offsetTop},getWidth:function(a){return a.clientWidth},getHeight:function(a){return a.clientHeight},getContentWidth:function(a){return a.scrollWidth},
getContentHeight:function(a){return a.scrollHeight},pushClassName:function(a,b){var c=a.className.split(" ");0>c.indexOf(b)&&(c[c.length]="."+b,a.className=c.join(" "))},toAbsolutePath:function(a){this.mPathConverter.innerHTML=cm.string.concat('<a href="',a,'" />');return this.mPathConverter.firstChild.href},createXhr:function(){return new XMLHttpRequest}}});
cm.Class.create({$name:"cm.cssImpl.AbsCssImpl",$define:{AbsCssImpl:function(){cm.css=this;if(cm.equal.isUndefined(this.mCss)){var a=document.getElementsByTagName("head")[0];if(a){var b=document.createElement("style");a.appendChild(b);this.mCss=b.sheet}}},destroy:function(){},ruleLength:function(){return this.mCss.cssRules.length},getRule:function(a){return this.mCss.cssRules[a]},appendRule:function(a,b,c){this.mCss.insertRule(cm.string.concat(a,"{",b,"}"),c)},removeRule:function(a){this.mCss.deleteRule(a)},
modifyRule:function(a,b){this.mCss.cssRules[a].style.cssText=b},gradientToString:function(){},applyPosition:function(a,b){var c=a.position;switch(b.position){case "":case "static":case "relative":b.position="relative";c.xFix(parseInt(b.left)).yFix(parseInt(b.top));break;case "fixed":case "absolute":c.xFix(parseInt(cm.dom.getX(a.parent))).yFix(parseInt(cm.dom.getY(a.parent)))}c.applied()},applyContainer:function(a,b){var c=a.container;c.widthFix(parseInt(b.width)).heightFix(parseInt(b.Height)).contentWidthFix(cm.dom.getContentWidth(a.parent)).contentHeightFix(cm.dom.getContentHeight(a.parent)).applied();
this.applyShape(c.shape(),b)},applyShape:function(a,b){a.topLeftFix(parseInt(b.borderTopLeftRadius));a.bottomLeftFix(parseInt(b.borderBottomLeftRadius));a.topRightFix(parseInt(b.borderTopRightRadius));a.bottomRightFix(parseInt(b.borderBottomRightRadius))},applyBackground:function(){},applyColor:function(a,b){var c=new String(b.backgroundColor);if("transparent"==c||""==c)a.argbFix(0);else for(var c=c.subString(c.indexOf("(")+1,c.length-2).split(","),d=["rFix","gFix","bFix","aFix"],e=0,f=c.length;e<
f;e++){var g=3>e?parseInt(c[e]):Number(c[e]);this.log(g);a[d[e]](g)}},colorToRgbString:function(a){return cm.string.concat("rgb(",a.r(),",",a.g(),",",a.b(),")")},colorToRgbaString:function(a){return cm.string.concat("rgba(",a.r(),",",a.g(),",",a.b(),",",a.aRatio(),")")},computedStyle:function(a,b){return this.d.defaultView.getComputedStyle(a,null).getPropertyValue(b)}}});